# Generated by Django 3.1.7 on 2021-05-06 18:28

from django.db import migrations, models
import django.db.models.deletion
import ivr.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_recorded', models.BooleanField(default=False, verbose_name='Metadata Recorded')),
                ('published', models.BooleanField(default=False, verbose_name='Content Published')),
                ('language', models.CharField(default='en', max_length=5, verbose_name='Content Language')),
                ('length', models.PositiveSmallIntegerField(blank=True, verbose_name='Content Length')),
                ('title_file', models.FileField(blank=True, upload_to=ivr.models.Content.content_directory_path, verbose_name='Title Audio File')),
                ('author_file', models.FileField(blank=True, upload_to=ivr.models.Content.content_directory_path, verbose_name='Author Audio File')),
                ('details_file', models.FileField(blank=True, upload_to=ivr.models.Content.content_directory_path, verbose_name='Details Audio File')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Content',
            },
        ),
        migrations.CreateModel(
            name='IVRUser',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_pin', models.CharField(max_length=8, verbose_name='Raw Pin')),
                ('register_complete', models.BooleanField(default=False, verbose_name='Completed Registration?')),
                ('focus', models.CharField(blank=True, choices=[('CL', 'Client'), ('VO', 'Volunteer')], default='CL', max_length=2, verbose_name='User Focus')),
                ('latest_number', models.CharField(max_length=15, verbose_name='Latest Phone Number')),
                ('latest_country', models.CharField(max_length=40, verbose_name='Latest Country')),
                ('language', models.CharField(default='en', max_length=5, verbose_name='Interface Language')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('login_at', models.DateTimeField(auto_now=True)),
                ('name_file', models.FileField(blank=True, upload_to=ivr.models.IVRUser.user_directory_path, verbose_name='Name Audio File')),
            ],
            options={
                'verbose_name': 'IVR User',
                'verbose_name_plural': 'IVR Users',
            },
        ),
        migrations.CreateModel(
            name='TempRecording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_sid', models.CharField(max_length=34, verbose_name='CallSid')),
                ('failed', models.BooleanField(default=False, verbose_name='Recording Failed')),
                ('recording_type', models.CharField(choices=[('AN', 'Account Name'), ('RT', 'Request Title'), ('RA', 'Request Author'), ('RD', 'Request Details')], default='RT', max_length=2, verbose_name='Recording Type')),
                ('recording_sid', models.CharField(blank=True, max_length=34, verbose_name='CallSid')),
                ('recording_url', models.URLField(blank=True, max_length=255, verbose_name='CallSid')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Twilio Recording in Queue',
                'verbose_name_plural': 'Twilio Recordings in Queue',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='book title')),
                ('author', models.CharField(max_length=50, null=True, verbose_name='book author')),
                ('genre', models.CharField(choices=[('SC', 'Science'), ('HI', 'History'), ('LI', 'Literature'), ('MA', 'Math'), ('BI', 'Biography'), ('RE', 'Reference')], max_length=2, null=True, verbose_name='genre')),
                ('files', models.CharField(max_length=200, verbose_name='file path')),
            ],
            options={
                'verbose_name': 'Title',
                'verbose_name_plural': 'Titles',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(blank=True, verbose_name='Position of the section in the Content')),
                ('length', models.PositiveSmallIntegerField(blank=True, verbose_name='Content Length')),
                ('title_file', models.FileField(blank=True, upload_to=ivr.models.Section.content_directory_path, verbose_name='Title Audio File')),
                ('segment_files', models.CharField(blank=True, max_length=150, verbose_name='Names of Segment Files')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ivr.content')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ivr.ivruser')),
            ],
            options={
                'verbose_name': 'section',
                'verbose_name_plural': 'sections',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False, verbose_name='Request Completed')),
                ('title_file', models.FileField(blank=True, upload_to=ivr.models.Request.request_directory_path, verbose_name='Title Audio File')),
                ('author_file', models.FileField(blank=True, upload_to=ivr.models.Request.request_directory_path, verbose_name='Author Audio File')),
                ('details_file', models.FileField(blank=True, upload_to=ivr.models.Request.request_directory_path, verbose_name='Details Audio File')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ivr.ivruser')),
            ],
            options={
                'verbose_name': 'Request for Content',
                'verbose_name_plural': 'Requests for Content',
            },
        ),
        migrations.AddField(
            model_name='content',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ivr.ivruser'),
        ),
        migrations.AddField(
            model_name='content',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ivr.request'),
        ),
    ]
