# Generated by Django 3.1.7 on 2021-04-27 18:07

from django.db import migrations, models
import ivr.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False, verbose_name='Request Completed')),
                ('title_file', models.FileField(upload_to=ivr.models.Request.request_directory_path, verbose_name='Title Audio File')),
                ('author_file', models.FileField(blank=True, upload_to=ivr.models.Request.request_directory_path, verbose_name='Author Audio File')),
                ('details_file', models.FileField(blank=True, upload_to=ivr.models.Request.request_directory_path, verbose_name='Details Audio File')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Request for Content',
                'verbose_name_plural': 'Requests for Content',
            },
        ),
        migrations.CreateModel(
            name='TempRecording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_sid', models.CharField(max_length=34, verbose_name='CallSid')),
                ('failed', models.BooleanField(default=False, verbose_name='Recording Failed')),
                ('recording_type', models.CharField(choices=[('AN', 'Account Name'), ('RT', 'Request Title'), ('RA', 'Request Author'), ('RD', 'Request Details')], default='RT', max_length=2, verbose_name='Recording Type')),
                ('recording_sid', models.CharField(blank=True, max_length=34, verbose_name='CallSid')),
                ('recording_url', models.URLField(blank=True, max_length=255, verbose_name='CallSid')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Twilio Recording in Queue',
                'verbose_name_plural': 'Twilio Recordings in Queue',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='book title')),
                ('author', models.CharField(max_length=50, null=True, verbose_name='book author')),
                ('genre', models.CharField(choices=[('SC', 'Science'), ('HI', 'History'), ('LI', 'Literature'), ('MA', 'Math'), ('BI', 'Biography'), ('RE', 'Reference')], max_length=2, null=True, verbose_name='genre')),
                ('files', models.CharField(max_length=200, verbose_name='file path')),
            ],
            options={
                'verbose_name': 'Title',
                'verbose_name_plural': 'Titles',
            },
        ),
    ]
