# Generated by Django 3.1.7 on 2021-04-26 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempRecording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_sid', models.CharField(max_length=34, verbose_name='CallSid')),
                ('completed', models.BooleanField(default=True, verbose_name='Recording Completed')),
                ('recording_sid', models.CharField(max_length=34, verbose_name='CallSid')),
                ('recording_url', models.URLField(max_length=255, verbose_name='CallSid')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Twilio Recording in Queue',
                'verbose_name_plural': 'Twilio Recordings in Queue',
            },
        ),
    ]
