# Generated by Django 3.2 on 2021-05-06 16:40

from django.db import migrations, models
import django.db.models.deletion
import ivr.models


class Migration(migrations.Migration):

    dependencies = [
        ('ivr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_recorded', models.BooleanField(default=False, verbose_name='Metadata Recorded')),
                ('published', models.BooleanField(default=False, verbose_name='Content Published')),
                ('language', models.CharField(default='en', max_length=5, verbose_name='Content Language')),
                ('length', models.PositiveSmallIntegerField(blank=True, verbose_name='Content Length')),
                ('title_file', models.FileField(blank=True, upload_to=ivr.models.Content.content_directory_path, verbose_name='Title Audio File')),
                ('author_file', models.FileField(blank=True, upload_to=ivr.models.Content.content_directory_path, verbose_name='Author Audio File')),
                ('details_file', models.FileField(blank=True, upload_to=ivr.models.Content.content_directory_path, verbose_name='Details Audio File')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Content',
            },
        ),
        migrations.AddField(
            model_name='request',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ivr.ivruser'),
        ),
        migrations.AlterField(
            model_name='ivruser',
            name='language',
            field=models.CharField(default='en', max_length=5, verbose_name='Interface Language'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(blank=True, verbose_name='Position of the section in the Content')),
                ('length', models.PositiveSmallIntegerField(blank=True, verbose_name='Content Length')),
                ('title_file', models.FileField(blank=True, upload_to=ivr.models.Section.content_directory_path, verbose_name='Title Audio File')),
                ('segment_files', models.CharField(blank=True, max_length=150, verbose_name='Names of Segment Files')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ivr.content')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ivr.ivruser')),
            ],
            options={
                'verbose_name': 'section',
                'verbose_name_plural': 'sections',
            },
        ),
        migrations.AddField(
            model_name='content',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ivr.ivruser'),
        ),
        migrations.AddField(
            model_name='content',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ivr.request'),
        ),
    ]
