# Generated by Django 3.1.7 on 2021-03-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester', models.CharField(max_length=10)),
                ('creator', models.CharField(max_length=10)),
                ('head', models.TextField()),
                ('body', models.TextField()),
                ('digits', models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Contents',
            },
        ),
    ]
