# Generated by Django 3.1.7 on 2021-04-04 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='book title')),
                ('author', models.CharField(max_length=50, null=True, verbose_name='book author')),
                ('genre', models.CharField(choices=[('SC', 'Science'), ('HI', 'History'), ('LI', 'Literature'), ('MA', 'Math'), ('BI', 'Biography'), ('RE', 'Reference')], max_length=2, null=True, verbose_name='genre')),
                ('files', models.FilePathField(null=True, path='/home/tim/Documents/GitHub/BeMyReader/ivr/media/<built-in function id>/')),
            ],
            options={
                'verbose_name': 'Title',
                'verbose_name_plural': 'Titles',
            },
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
