# Generated by Django 3.1.7 on 2021-04-05 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0002_auto_20210404_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='files',
            field=models.CharField(max_length=200, verbose_name='file path'),
        ),
    ]
